### ISSUE TITLE
[3pt] Bug corrections

### ISSUE THREAD

**Issue by VelzckC0D3** [VelzckC0D3/Land-Rover-E-Commerce#20]
There's a minor bug which causes that whenever refreshing '/reservations' & 'vehicle details' the information fetched is lost. 

https://github.com/VelzckC0D3/Land-Rover-E-Commerce/assets/92229666/fa86b005-1465-414e-a24f-95d6087ce9c8

**Comment by Danfall369** [comment]
Here is the [P.R](https://github.com/VelzckC0D3/Land-Rover-E-Commerce/issues/20) with Fix that bug and something makes better optimization:
